### ISSUE TITLE
Error while running examples/navigation npm run serve, page displayed blank

### ISSUE THREAD

**Issue by preetb123** [redux-observable/redux-observable#123]
I am getting following error when `npm run serve` is run. I tried upgrading the version of `redux-observable` and `rxjs` but that didn't help. Also `http://localhost:8080/` shows a blank screen with same error in developers console.

```
ERROR in ./index.js
Module build failed: ReferenceError: Unknown plugin "transform-function-bind" specified in "/Users/preetam/Documents/react_samples/redux-observable/.babelrc" at 0, attempted to resolve relative to "/Users/preetam/Documents/react_samples/redux-observable"
    at /Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/preetam/Documents/react_samples/redux-observable/examples/navigation/node_modules/babel-loader/index.js:131:12)
 @ multi main
```

**Comment by jayphelps** [comment]
I'll have to confirm later, but it appears when you try to run the demo, babel is traversing the parent directory tree and finding the `.babelrc` from the redux-observable project itself and trying to use it for the navigation example app, which is wrong. If that's the case, I'll figure out how to get it to stop doing that.

In the meantime, navigate to `~/Documents/react_samples/redux-observable` and `npm install` the redux-observable dependencies themselves. Which should allow it to work, even though it doesn't actually need to depend on it.

**Comment by preetb123** [comment]
that worked. thanks!

**Comment by jayphelps** [comment]
Fixed the example to not use babelrc from parent dirs in https://github.com/redux-observable/redux-observable/commit/338423788d8430cc86f0286ad0d4ae5aa20d4010

Thanks for reporting.
