### ISSUE TITLE
Uncaught TypeError: epic.apply is not a function

### ISSUE THREAD

**Issue by karfield** [redux-observable/redux-observable#276]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

```
bundle.js:47432 Uncaught TypeError: epic.apply is not a function
    at http://localhost:8080/bundle.js:47432:26
    at Array.map (native)
    at http://localhost:8080/bundle.js:47431:115
    at MapSubscriber.project (http://localhost:8080/bundle.js:47372:96)
    at MapSubscriber._next (http://localhost:8080/bundle.js:5864:35)
    at MapSubscriber.Subscriber.next (http://localhost:8080/bundle.js:611:18)
    at Subject.next (http://localhost:8080/bundle.js:1444:25)
    at http://localhost:8080/bundle.js:47384:13
    at http://localhost:8080/bundle.js:17855:14
    at http://localhost:8080/bundle.js:45393:100
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

my configureStore.js

```
import { createStore, applyMiddleware, compose } from 'redux';
import { createEpicMiddleware } from 'redux-observable';
import { routerMiddleware } from 'react-router-redux';

import * as containers from './containers'
import rootReducer from './reducers'
import rootEpic from './epics'

const epicMiddleware = createEpicMiddleware(rootEpic);
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(
    rootReducer,
    composeEnhancers(
        applyMiddleware(
            epicMiddleware,
            routerMiddleware(browserHistory)
        )
    )
);
```

epcs

```
import {combineEpics} from 'redux-observable';
import userLogin from "./userAuth";

export default combineEpics(
    userLogin,
)
```

**What is the expected behavior?**

No error

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

```
    "history": "^4.6.3",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-redux": "^4.0.8",
    "redux": "^3.7.1",
    "redux-observable": "^0.14.1",
    "rxjs": "^5.4.2",
```

Browser: Version 59.0.3071.115 (Official Build) (64-bit)

OS: macOs 10.12.5

**Comment by aarosil** [comment]
I have seen this, usually when one of the epics was undefined, check
userAuth.js & everything is exported/imported correctly

**Comment by jayphelps** [comment]
Sorry there's not enough info to go on. 99.9% sure this is a bug in your app, but happy to help if you can provide some way to reproduce. I agree that you likely are passing something that is unintentionally undefined. Pause your debugger and walk the stack back to see where the undefined value came from.

**Comment by IanVS** [comment]
FWIW, I got this error when I mistakenly provided an object to `combineEpics` like:

```js
export const rootEpic = combineEpics({
     foo: fooEpic,
});
```

I mistakenly assumed it had the same signature as `combineReducers`.  If this is a common mistake, it might make sense to detect it and throw a nicer error message.

**Comment by jayphelps** [comment]
@IanVS that's being tracked in #58 but I don't have the cycles to devout to it right now since it's not something I need personally--but if someone else PR'd it, we likely would accept it. Passing in an object is really weird because the keys are meaningless (unlike in combineReducers where they're meaningful), but people seem to do it so much we might as well just live with supporting it.

**Comment by jayphelps** [comment]
Closing due to inactivity 💃

**Comment by pasih** [comment]
For posterity, another possibility is that you're passing an Observable to combineEpics(), rather than a function. Say, `const sth = Observable.combineLatest(...).map(...)` and later down the road `combineEpics(..., sth)`.

**Comment by eightyfive** [comment]
Maybe accept an `Array` as well?

Just my 2 cents cause I went down the rabbit hole to find out what was wrong for few (too many!) minutes.

**Comment by sagarkalokhe09** [comment]
i was facing same issue. try using spread operator like ...obj while passing epic to combineepic
