### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of (0 , _redux.applyMiddleware)

### ISSUE THREAD

**Issue by amjadmaxis2018** [redux-observable/redux-observable#636]
hello everyone im facing this issue when im trying doing test for a simple code 

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of (0 , _redux.applyMiddleware)

      15 | 
      16 | export const testStore = (initialState) => {
    > 17 |     const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore);
         |                                       ^
      18 |     return createStoreWithMiddleware(rootReducer, initialState);
      19 | };
      20 | 

      at testStore (src/Utils/index.js:17:39)
      at Object.<anonymous>.it (src/pages/LogInPage/.spec.js:8:17)
```

test code 

```

import { applyMiddleware, createStore } from 'redux';
import rootReducer from '../store/reducers';
import { middlewares } from '../createStore';

export const findByTestAtrr = (component, attr) => {
    const wrapper = component.find(`[data-test='${attr}']`);
    return wrapper;
};



export const testStore = (initialState) => {
    const createStoreWithMiddleware = applyMiddleware(...middlewares)(createStore);
    return createStoreWithMiddleware(rootReducer, initialState);
};


```

```
import React from 'react';
import ReactDOM from 'react-dom';
import LogInPage from './LogInPage';
import { testStore } from '../../Utils';

it('renders without crashing', () => {
  const div = document.createElement('div');
  const store = testStore();
  ReactDOM.render(<LogInPage />, div);
});
```

**Comment by jayphelps** [comment]
Still having this problem? I don't immediately see the cause, but the error also _really_ doesn't make sense. Seems like some sort of problem with the way it's being compiled because what you show has no reason to need for `'Symbol.iterator` on `(0 , _redux.applyMiddleware)`, instead it should be looking for an iterator on the `middleware` since that's what you're spreading.

**Comment by VisheshSingh** [comment]
I suspect you may have forgotten to export middleware from createstore.js file
